export const QUERY_KEYS = {
    CLASSIFICATIONS: 'classifications',
    PUBLICATIONS: 'publications',
    PUBLICATION_STATS: 'publication_stats',
    REPORT_RESUME: 'report_resume',
    CLASSIFICATION_CONFIDENCE: 'classification_confidence',
    CLASSIFICATION_PERCENTAGE: 'classification_percentage',
    WEBHOOK: 'webhook',
    WEBHOOK_HISTORY: 'webhook_history',
    PROCESSES: 'processes',
    PROCESS: 'process',
    PROCESS_BATCHES: 'process_batches',
    PROCESS_BATCH: 'process_batch',
    BATCHES: 'batches',
    BATCH: 'batch',
    REPORT: 'report',
} as const;