export const QUERY_KEYS = {
    CLASSIFICATIONS: 'classifications',
    PUBLICATIONS: 'publications',
    PUBLICATIONS_V2: 'publications_v2',
    PUBLICATION_V2: 'publication_v2',
    CASE_TYPES_V2: 'case_types_v2',
    CLASSIFICATIONS_V2: 'classifications_v2',
    RECIPIENTS_V2: 'recipients_v2',
    CATEGORIES_V2: 'categories_v2',
    PUBLICATIONS_V2_TOTAL: 'publications_v2_total',
    PUBLICATIONS_V2_STATISTICS: 'publications_v2_statistics',
    PUBLICATIONS_V2_PROCESSING_STATUS: 'publications_v2_processing_status',
    PUBLICATION_STATS: 'publication_stats',
    REPORT_RESUME: 'report_resume',
    CLASSIFICATION_CONFIDENCE: 'classification_confidence',
    CLASSIFICATION_PERCENTAGE: 'classification_percentage',
    WEBHOOK: 'webhook',
    WEBHOOK_HISTORY: 'webhook_history',
    PROCESSES: 'processes',
    PROCESS: 'process',
    PROCESS_BATCHES: 'process_batches',
    PROCESS_BATCH: 'process_batch',
    BATCHES: 'batches',
    BATCH: 'batch',
    REPORT: 'report',
    DOCUMENTS: 'documents',
} as const;