export const PUBLICATION_STATUS = {
    PENDING: 1,
    COMPLETED: 2,
    ERROR: 3,
    PROCESSING: 4,
}

export const PUBLICATION_CASE_TYPE = {
    CIVIL: 1,
    CRIMINAL: 2,
}

export const CLASSIFICATION_STATUS = {
    PENDING: 1,
    CONFIRMED: 2,
    REJECTED: 3,
    RECLASSIFIED: 4,
}